owner: cpressland
repo: upptime

sites:
  - name: Jellyfin
    url: https://jellyfin.cpressland.io/web/

assignees:
  - cpressland

status-website:
  cname: status.cpressland.io
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "CPressland.io Status"
  themeUrl: https://status.cpressland.io/catppuccin.css
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
